#!/bin/bash
JS="../JavaScript/Library"
DIR=$(cd `dirname $0` && pwd)

# DynamicMatcher
packager build DynamicMatcher/* +use-only DynamicMatcher > "$DIR/$JS/PowerTools/DynamicMatcher.js"

# Class-Extras
packager build Class-Extras/* +use-only Class-Extras > "$DIR/$JS/PowerTools/Class-Extras.js"

# History
packager build History/History +use-only History > "$DIR/$JS/PowerTools/History.js"

# Router
packager build Router/Router +use-only Router > "$DIR/$JS/PowerTools/Router.js"

# Custom-Event
packager build Custom-Event/* +use-only Custom-Event > "$DIR/$JS/PowerTools/Custom-Event.js"

# Mootilities
packager build Mootilities/Queue +use-only Mootilities > "$DIR/$JS/PowerTools/Queue.js"

# Mobile
packager build Mobile/Browser.Mobile Mobile/Click Mobile/Swipe +use-only Mobile > "$DIR/$JS/PowerTools/Mobile.js"

# EventStack
packager build EventStack/* +use-only EventStack EventStack.OuterClick > "$DIR/$JS/PowerTools/EventStack.js"

# Form AutoGrow
packager build Form-AutoGrow/* +use-only Form-AutoGrow > "$DIR/$JS/PowerTools/AutoGrow.js"

## MooTools Core
packager build Element Element.Event Class.Extras More/Element.Event.Pseudos +use-only Core More -blocks 1.2compat 1.3compat ltIE9 ltIE8 !ES5 ltFF4 > "$DIR/$JS/Core.js"
