#!/bin/bash
JS="../JavaScript"
OUTPUT="../App/JavaScript"
DIR=$(cd `dirname $0` && pwd)

$DIR/modulr --watch --out "$DIR/$OUTPUT/build.js" "App" --path "$DIR/$JS/:$DIR/$JS/Library:$DIR/$JS/Library/PowerTools:$DIR/$JS/Library/ThirdParty" -e "dev" $@
