#!/bin/bash
DIR=$(cd `dirname $0` && pwd)
node $DIR/watch --prod --once
cd $DIR/../Server/
rm -f *.zip

for f in $(find "./" -mindepth 1 -maxdepth 1 -type d ); do
  zip -r "$f.zip" "$f" -x "$f/.*"
done
