#!/usr/bin/env node

var fs = require('fs');
var modulr = require('modulr');
var path = require('path');

var defaultOptions = {
  allowDirModules: true,
  minify: false,
  resolveIdentifiers: true,
  paths: ['.'],
  environment: 'prod' // or 'dev', defaults to undefined
};

exports.build = function(file, options) {
  file = path.resolve(file);
  var object = {};

  for (var key in options) object[key] = options[key];
  for (var key in defaultOptions) {
    if (!object[key]) object[key] = defaultOptions[key];
  }

  object.paths.forEach(function(p) {
    fs.lstat(path.resolve(p) + '/' + object.main + '.js', function(err, stat){
      if (err) return;
      if (!stat.isFile()) return;

      modulr.build(object.main, object, function(err, result) {
        if (err) {
          console.log(err.stack);
          return;
        }
        require('fs').writeFileSync(file, result.output, 'utf8');
        console.log('  \033[90mcompiled\033[0m %s', file);
      });
    });
  });
};
