#!/usr/bin/env node

var fs = require('fs');
var exec = require('child_process').exec;
var path = require('path');
var sys = require('sys');

var shell = require('shelljs');
var watchMonitor = require('watch');

var config = require('./config');
var modulr = require('./modulr');
var projectPath = path.resolve(__dirname, '../');

var compileForProduction = false;
var once = false;

var args = process.argv.slice(2);
while (args.length) {
  var arg = args.shift();
  switch (arg) {
    case '--prod':
      compileForProduction = true;
      break;
    case '--once':
      once = true;
      break;
  }
}

var getCommitHash = function(fn) {
  exec('git rev-parse --verify HEAD', function(error, stdout) {
    fn(stdout.trim());
  });
};

var run = function(command, fn) {
  exec(projectPath + '/' + command, function(error, stdout, stderr) {
    stdout = stdout.trim();
    if (stdout) sys.puts('  ' + stdout);

    if (error) {
      console.log(stderr);
      return;
    }

    if (fn) fn();
  });
};

var attach = function(monitor, listener) {
  monitor.on('created', listener);
  monitor.on('changed', listener);
  monitor.on('removed', listener);
};

var watch = function(directory, fn) {
  fn();
  if (once) return;

  watchMonitor.createMonitor(directory, {interval: 300}, function(monitor) {
    attach(monitor, fn);
  });
};

var writeVersion = function(hash) {
  fs.writeFile(config.VersionFile, "window.__APP_VERSION='" + hash + "';");
};

var previousHash;

var compileTemplates = function() {
  run('node_modules/.bin/handlebars "' + config.Templates + '" -f "' + config.TemplatesFile + '" -c "Handlebars"', function() {
    console.log("  \033[90mcompiled\033[0m " + config.TemplatesFile);
  });
};

var compileSTYL = function() {
  shell.rm('-f', path.resolve(config.Server, '*-*.css'));
  run('node_modules/.bin/stylus --use "' + path.resolve(projectPath, 'node_modules/nib/lib/nib.js') + '" --out "' + config.Server + '" --use url --with "' + JSON.stringify(config.StylusOptions).replace(/"/g, '\\\"') + '" "' + config.STYL_Server + '"' + (compileForProduction ? ' -c' : ''), function() {
    getCommitHash(function(hash) {
      if (previousHash && hash != previousHash) compileJS();
      previousHash = hash;
      writeVersion(hash);
      shell.mv('-f', path.resolve(config.Server, 'App.css'), path.resolve(config.Server, config.ServerCSSFile.replace(/\{hash\}/, hash)));
    });
  });
  run('node_modules/.bin/stylus --use "' + path.resolve(projectPath, 'node_modules/nib/lib/nib.js') + '" --out "' + config.App + '" --use url --with "' + JSON.stringify(config.StylusOptions).replace(/"/g, '\\\"') + '" "' + config.STYL_Client + '"');
  shell.cp('-f', path.resolve(config.App, 'App.css'), config.AndroidClient);
};

var compileJS = function() {
  shell.rm('-f', path.resolve(config.Server, '*-*.js'));
  getCommitHash(function(hash) {
    if (previousHash && hash != previousHash) compileSTYL();
    previousHash = hash;
    writeVersion(hash);
    modulr.build(path.resolve(config.Server, config.ServerJSFile.replace(/\{hash\}/, hash)), compileForProduction ? config.ServerJSProductionOptions : config.ServerJSOptions);
  });
};

watch(config.Templates, compileTemplates);
watch(config.STYL, compileSTYL);
watch(config.JS, compileJS);
